[lastfm_api]
api_key = "api_key"
api_secret = "api_secret"

[lastfm]
username = "username"
password = "password"

[listenbrainz]
token = "token"

[video]
link = "https::///www.youtube.com/something"
second_link = "https::///www.youtube.com/something"

[server]
link = "http://127.0.0.1:8888"

[server_settings]
token_db = "token.db"
port = 8888